### PR TITLE
Restructure site to allow easy translations

### PR DESCRIPTION
**Pull request by GjjvdBurg**
See also pull requests #63 and #64. 

This pull requests differs from the others in that it gets the translations variable from the `page` instead of the `layout`. This is to because Github uses Jekyll 3.0.4.

Additionally, in this pull request the HTML language code is set to the `page.lang` variable.

### CODE REVIEW

**Comment by GjjvdBurg** [comment]
@leo, I think the side-menu doesn't work now (at About etc.)

**Comment by leo** [comment]
Oh, good catch! The variables not seem to be outputted correctly:

screen shot 2016-04-26 at 20 35 58

**Comment by GjjvdBurg** [comment]
@leo On it!

**Comment by GjjvdBurg** [comment]
@leo I can't find a way to get the translations defined in `_layouts/default.html` to be available in `_layouts/page.html`. However, they are available in the actual pages, which is why they do show up in all the other links. One way to solve this, would be to define the translations in the `_config.yml` file, instead of in `default.html`. Which, come to think of it, also might make more sense. Since this issue is due to different Jekyll versions, defining the translations in `_config.yml` as front matter defaults may also be more robust (in case Github pages decides to update Jekyll in the future). Agreed?

**Comment by leo** [comment]
@GjjvdBurg Yep! 😊

**Comment by GjjvdBurg** [comment]
It would look like this in the `_config.yml` file:

```
defaults:
  -
    scope:
      path: 'en'
    values:
      lang: 'en'
      translations:
        videos:
          title: 'Start'
          menu-title: 'Videos'
          mobile-title: 'Machines'
        about:
          link: 'about'
          title: 'About'
```

The added `translations` level is not strictly necessary, but I think it helps with readability, right?

**Comment by leo** [comment]
@GjjvdBurg Yep, definitely! 👍

**Comment by GjjvdBurg** [comment]
@leo New pull request added. Probably easiest to revert this one and merge the other automatically.

**Pull request merged**
