### PR TITLE
Dynamic news

### PR DESCRIPTION
**Pull request by b-n**
Now loads news with #preciousplastic tag from davehakkens.nl. On clicking, will actually send to the article, rather than the community link on dave hakkens.

Note: the images are all of different heights/dimensions, and haven't tried to make them "cover" images. Let me know if you want me to adjust the picture css so the images are all the same height etc.

screen shot 2017-10-25 at 16 43 40

### CODE REVIEW

**Comment by davehakkens** [comment]
awesome! Yes would be amazeballs if we can make them the same height

**Comment by b-n** [comment]
All good, I'll see what I can do this evening 👍

**Comment by b-n** [comment]
screen shot 2017-10-29 at 09 35 02
Fixed and ready to merge 😄

**Comment by davehakkens** [comment]
amazing

**Pull request merged**
