### PR TITLE
Restructure site for translations

### PR DESCRIPTION
**Pull request by GjjvdBurg**
This restructures the site for the translations (#63, #64, #66). Translations are now defined in `_config.yml`.

### CODE REVIEW

**Comment by leo** [comment]
Seems like everything works fine! 😊

**Comment by GjjvdBurg** [comment]
Great!

**Comment by leo** [comment]
@GjjvdBurg Thank you again for all of your effort! We'll make sure to mention you somewhere in the guide afterwards.

**Comment by GjjvdBurg** [comment]
@leo No problem! Took a few iterations but we've got it! :) If there's anything else I can help with let me know.

**Comment by leo** [comment]
@GjjvdBurg Just noticed that most other websites keep the url the same and just prepend the language prefix: http://www.apple.com/de/ipad-pro/experience/

Would you mind removing all of the `link` properties so that contributors aren't able to adjust the link anymore? Thank would be really awesome! 😊

**Comment by GjjvdBurg** [comment]
@leo Sure thing! I'll make a pull request when it's ready.

**Pull request merged**
