### PR TITLE
Restructure site to allow for easy translations

### PR DESCRIPTION
**Pull request by GjjvdBurg**
This pull request is the same as pull request #63, with the difference that it is correctly rebased on the `gh-pages` branch.

### CODE REVIEW

**Comment by leo** [comment]
Hell yeah! :metal: Just a small thing left before we can merge it: The active state of the submenu ("About", "Thanks", etc.) doesn't seem to work.

Just apply the changes to the "dev" branch, the PR will reflect them (I'm sure you already know that).

screen shot 2016-04-24 at 11 44 14

**Comment by GjjvdBurg** [comment]
@leo thanks for the thorough check! I believe it is fixed now

**Comment by leo** [comment]
@GjjvdBurg Thank you for all of your effort! I'll make sure to add a guide on how to contribute new translations later. 😊

**Comment by leo** [comment]
@GjjvdBurg Just merged the PR into master at looked at the output and it seemed like everything related to string interpolation was broken:

```
{{layout.translations.[page.lang].thanks.link}}
```

While this worked locally for me, it looks like GH either doesn't support this on the server (for security reasons) or they simply haven't [upgraded Jekyll](https://pages.github.com/versions/) yet. Any ideas?

I've already tried it with a static variable, but this [doesn't seem to work](https://github.com/hakkens/precious-plastic/issues/65) either:

```
{% assign lang = "en" %}
{{layout.translations.[lang].thanks.link}}
```

**Comment by GjjvdBurg** [comment]
@leo I've just installed the Jekyll version GitHub uses (3.0.4) and I can reproduce the behavior you're reporting. I'll let you know as soon as I have fixed it.

**Comment by GjjvdBurg** [comment]
@leo I have fixed it now on my `dev` branch. The problem was that in Jekyll 3.0.4 the translations come from the `page` variable, instead of the `layout` variable. In the end I ended up using the instructions [here](https://help.github.com/articles/setting-up-your-github-pages-site-locally-with-jekyll/) to get the same software locally as is used by GitHub.

Shall I submit a new pull request?

**Comment by leo** [comment]
@GjjcdBurg Great! Yes, please :)

**Pull request merged**
